patch -p1 < ./0001-fs-writeback-Add-helper-function-to-start-writeback-.patch
patch -p1 < ./0002-ext4-flush-delalloc-blocks-when-space-is-low.patch
patch -p1 < ./0003-ext4-fix-async-i-o-writes-beyond-4GB-to-a-sparse-fil.patch
patch -p1 < ./0004-ext4-correctly-calculate-number-of-blocks-for-fiemap.patch
patch -p1 < ./0005-ext4-Fix-potential-quota-deadlock.patch
patch -p1 < ./0006-jbd-jbd-debug-and-jbd2-debug-should-be-writable.patch
patch -p1 < ./0007-ext4-replace-BUG-with-return-EIO-in-ext4_ext_get_blo.patch
patch -p1 < ./0008-ext4-jbd2-Add-barriers-for-file-systems-with-exernal.patch
patch -p1 < ./0009-ext4-Eliminate-potential-double-free-on-error-path.patch
patch -p1 < ./0010-ext4-return-correct-wbc.nr_to_write-in-ext4_da_write.patch
patch -p1 < ./0011-ext4-Ensure-zeroout-blocks-have-no-dirty-metadata.patch
patch -p1 < ./0012-ext4-Patch-up-how-we-claim-metadata-blocks-for-quota.patch
patch -p1 < ./0013-ext4-Fix-accounting-of-reserved-metadata-blocks.patch
patch -p1 < ./0014-ext4-Calculate-metadata-requirements-more-accurately.patch
patch -p1 < ./0015-ext4-Handle-EDQUOT-error-on-write.patch
patch -p1 < ./0016-ext4-Fix-quota-accounting-error-with-fallocate.patch
patch -p1 < ./0017-ext4-Drop-EXT4_GET_BLOCKS_UPDATE_RESERVE_SPACE-flag.patch
patch -p1 < ./0018-ext4-Use-bitops-to-read-modify-EXT4_I-inode-i_state.patch
patch -p1 < ./0019-ext4-Fix-BUG_ON-at-fs-buffer.c-652-in-no-journal-mod.patch
patch -p1 < ./0020-ext4-Add-flag-to-files-with-blocks-intentionally-pas.patch
patch -p1 < ./0021-ext4-Fix-fencepost-error-in-chosing-choosing-group-v.patch
patch -p1 < ./0022-ext4-fix-error-handling-in-migrate.patch
patch -p1 < ./0023-ext4-explicitly-remove-inode-from-orphan-list-after-.patch
patch -p1 < ./0024-ext4-Handle-non-empty-on-disk-orphan-link.patch
patch -p1 < ./0025-ext4-make-offset-consistent-in-ext4_check_dir_entry.patch
patch -p1 < ./0026-ext4-Fix-insertion-point-of-extent-in-mext_insert_ac.patch
patch -p1 < ./0027-ext4-Fix-the-NULL-reference-in-double_down_write_dat.patch
patch -p1 < ./0028-ext4-Code-cleanup-for-EXT4_IOC_MOVE_EXT-ioctl.patch
patch -p1 < ./0029-ext4-Fix-estimate-of-of-blocks-needed-to-write-indir.patch
patch -p1 < ./0030-ext4-Fixed-inode-allocator-to-correctly-track-a-flex.patch
patch -p1 < ./0031-ext4-Fix-possible-lost-inode-write-in-no-journal-mod.patch
patch -p1 < ./0032-ext4-Fix-buffer-head-leaks-after-calls-to-ext4_get_i.patch
patch -p1 < ./0033-ext4-Issue-the-discard-operation-before-releasing-th.patch
patch -p1 < ./0034-ext4-check-missed-return-value-in-ext4_sync_file.patch
patch -p1 < ./0035-ext4-fix-memory-leaks-in-error-path-handling-of-ext4.patch
patch -p1 < ./0036-ext4-Remove-unnecessary-call-to-ext4_get_group_desc-.patch
patch -p1 < ./0037-ext4-rename-ext4_mb_release_desc-to-ext4_mb_unload_b.patch
patch -p1 < ./0038-ext4-allow-defrag-EXT4_IOC_MOVE_EXT-in-32bit-compat-.patch
patch -p1 < ./0039-ext4-fix-quota-accounting-in-case-of-fallocate.patch
patch -p1 < ./0040-ext4-check-s_log_groups_per_flex-in-online-resize-co.patch
patch -p1 < ./0041-ext4-don-t-return-to-userspace-after-freezing-the-fs.patch
patch -p1 < ./0042-ext4-stop-issuing-discards-if-not-supported-by-devic.patch
patch -p1 < ./0043-ext4-don-t-scan-accumulate-more-pages-than-mballoc-w.patch
patch -p1 < ./0044-ext4-Do-not-zero-out-uninitialized-extents-beyond-i_.patch
patch -p1 < ./0045-ext4-clean-up-inode-bitmaps-manipulation-in-ext4_fre.patch
patch -p1 < ./0046-ext4-init-statistics-after-journal-recovery.patch
patch -p1 < ./0047-ext4-Remove-extraneous-newlines-in-ext4_msg-calls.patch
patch -p1 < ./0048-ext4-Prevent-creation-of-files-larger-than-RLIMIT_FS.patch
patch -p1 < ./0049-ext4-check-for-a-good-block-group-before-loading-bud.patch
patch -p1 < ./0050-ext4-Show-journal_checksum-option.patch
patch -p1 < ./0051-ext4-Use-bitops-to-read-modify-i_flags-in-struct-ext.patch
patch -p1 < ./0052-ext4-Avoid-crashing-on-NULL-ptr-dereference-on-a-fil.patch
patch -p1 < ./0053-ext4-Clear-the-EXT4_EOFBLOCKS_FL-flag-only-when-warr.patch
patch -p1 < ./0054-ext4-restart-ext4_ext_remove_space-after-transaction.patch
patch -p1 < ./0055-ext4-Conditionally-define-compat-ioctl-numbers.patch
patch -p1 < ./0056-ext4-Fix-compat-EXT4_IOC_ADD_GROUP.patch
patch -p1 < ./0057-ext4-Make-fsync-sync-new-parent-directories-in-no-jo.patch 